### ISSUE TITLE
Connection failed when enabling TLS

### ISSUE THREAD

**Issue by jpatigny** [ParagonIaC/terraform-provider-activedirectory#19]
First of all thank you for making this provider.
The TLS part is actually mandatory for me.

**Terraform Version**

Terraform v0.12.13

**Affected Resource(s)**

Please list the affected resources and data sources.

* activedirectory_provider

**Terraform Configuration Files**

Information about code formatting: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

```hcl
# Configure the AD Provider
provider "activedirectory" {
  host     = "mydc.domain.local"
  domain   = "domain.local"
  use_tls  = true
  user     = var.user
  password = var.password
}
```
**Expected Behavior**

The plan should be executed

**Actual Behavior**

Plan not executed as terraform cannot access the active directory

**Steps to Reproduce**

Please list the steps required to reproduce the issue.

1. `terraform plan`

Error: providerConfigure - connection to active directory failed: connect - failed to use secure connection: LDAP Result Code 200 "Network Error": TLS handshake failed (tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config)

**Comment by adlerrobert** [comment]
Hi @jpatigny, thanks for your feedback. Let me have a look into this.

**Comment by adlerrobert** [comment]
@jpatigny, can you check if the last merge solves your problem. Thanks. And sorry for the delay.

**Comment by jpatigny** [comment]
> @jpatigny, can you check if the last merge solves your problem. Thanks. And sorry for the delay.

Test sucessfull with terraform 12.20 using TLS !

You're the man ;-)

**Comment by jpatigny** [comment]
fixed
